In [1]:
import numpy as np

In [3]:
# Crear arreglo de 1 dimension con 5 elementos
arr1 = np.array([1,2,3,4,5,6])

print("Arreglo ID:", arr1)
print("Forma(shape): ", arr1.shape)
print("Tipo de datos (dtype)", arr1.dtype)

Arreglo ID: [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipo de datos (dtype) int32


In [7]:
# Cambiar la forma del arreglo a una matriz 2x3
arr2 = arr1.reshape((2,3))
print("Arreglo ID:\n", arr2)
print("Forma(shape): ", arr2.shape)
print("Tipo de datos (dtype)", arr2.dtype)

Arreglo ID:
 [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Tipo de datos (dtype) int32


In [8]:
# Crear una matriz con forma (4,4) con numeros aleatorios entre 0 y 1.
matrix = np.random.rand(4,4)
print("Arreglo ID:\n", matrix)
print("Forma(shape): ", matrix.shape)
print("Tipo de datos (dtype)", matrix.dtype)

Arreglo ID:
 [[0.73776744 0.90280699 0.46994849 0.09085845]
 [0.43617847 0.4280338  0.3664136  0.51373784]
 [0.77448573 0.78579249 0.44364488 0.83587452]
 [0.61025952 0.60771263 0.92228954 0.35101316]]
Forma(shape):  (4, 4)
Tipo de datos (dtype) float64


In [11]:
# Crear un arreglo de 2 dim a partir de una lista de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [12]:
# Crear un arreglo de ceros con una forma (3,4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# Crear un arreglo con unos con una forma (2,2)
arr = np.ones((2,2))
arr[1, 1] = 10
arr

array([[ 1.,  1.],
       [ 1., 10.]])

In [22]:
# Crear una matriz identidad
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# Crear un arreglo 3D de ceros con forma (2,3,4)
arr = np.zeros((2,3,4))
arr[0,1,2] = 5
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
arr = np.random.rand(2,5)
arr

array([[0.99127349, 0.13867521, 0.70094734, 0.19207855, 0.52487246],
       [0.73472065, 0.1525456 , 0.4999541 , 0.49503414, 0.17103676]])

In [36]:
arr.T

array([[0.99127349, 0.73472065],
       [0.13867521, 0.1525456 ],
       [0.70094734, 0.4999541 ],
       [0.19207855, 0.49503414],
       [0.52487246, 0.17103676]])

In [39]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [40]:
# Concatenar arreglos horizontalmente 
arr_h = np.hstack((arr1, arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
# Concatenar arreglos verticalmente
arr_v = np.vstack((arr1, arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [43]:
# Calcular la suma de elementos
suma = np.sum(arr)
suma

15

In [44]:
# Calcular el promedio de los elementos
promedio = np.mean(arr)
promedio

3.0

In [45]:
# Calcular la mediana
mediana = np.median(arr)
mediana

3.0

In [46]:
# Calcular el producto de los elementos
producto = np.prod(arr)
producto

120

In [47]:
# Desviacion estandar
des_est = np.std(arr)
des_est

1.4142135623730951

In [48]:
# Varianza
var = np.var(arr)
var

2.0

In [49]:
# Minimo de los elementos
minimo = np.min(arr)
# Maximo de los elementos
maximo = np.max(arr)
minimo, maximo

(1, 5)

In [50]:
# Calcular la suma acumulativa
cumsum = np.cumsum(arr)
cumsum

array([ 1,  3,  6, 10, 15])

In [51]:
# Suma element-wise
arr + arr

array([ 2,  4,  6,  8, 10])

In [52]:
# Resta element-wise
arr - arr

array([0, 0, 0, 0, 0])

In [53]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [54]:
arr / arr

array([1., 1., 1., 1., 1.])